--- #YAML:1.0
name:               POE-Loop-Event
version:            1.304
abstract:           Event.pm support for POE.
author:
    - Rocco Caputo <rcaputo@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
    POE::Test::Loops:     1.035
build_requires:
    ExtUtils::MakeMaker:  0
    POE::Test::Loops:     1.035
requires:
    Event:  1.13
    POE:    1.289
resources:
    license:     http://dev.perl.org/licenses/
    repository:  https://poe.svn.sourceforge.net/svnroot/poe/trunk/polo-event
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
